version: "3.8"

services:
  db:
    image: postgres:15
    container_name: deals-db
    environment:
      POSTGRES_DB: dealsdb
      POSTGRES_USER: deals
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U deals -d dealsdb"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - deals-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: deals-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/dealsdb
      SPRING_DATASOURCE_USERNAME: deals
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    volumes:
      - sdet-assignment_app_logs:/app/logs
#      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - deals-network

volumes:
  db_data:
  sdet-assignment_app_logs:
    external: true

networks:
  deals-network:
    driver: bridge