version: "3.8"

services:
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: deals-network
      DOCKER_INFLUXDB_INIT_ORG: myorg
      DOCKER_INFLUXDB_INIT_BUCKET: k6
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    networks:
      - deals-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: deals-network
      GF_USERS_ALLOW_SIGN_UP: "false"
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    networks:
      - deals-network
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning

  k6:
    image: grafana/k6:0.48.0
    container_name: k6
    depends_on:
      - influxdb
    volumes:
      - ./k6:/scripts
    command: run --out influxdb=http://admin:deals-network@influxdb:8086/k6 /scripts/perf_api_stress.js
    networks:
      - deals-network

volumes:
  influxdb_data:
  grafana_data:

networks:
  deals-network:
    driver: bridge