apiVersion: 1
datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: k6
    user: admin
    password: admin123
    isDefault: true
    jsonData:
      organization: myorg
      version: Flux